-- Eliminar las tablas si existen
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;

-- Crear la tabla categoria
CREATE TABLE categoria (
    idCategoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcionCategoria VARCHAR(50) NOT NULL,
    nombreCategoria VARCHAR(50) NOT NULL
);

-- Crear la tabla producto
CREATE TABLE producto (
    idProducto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreProducto VARCHAR(50) NOT NULL,
    descripcionProducto VARCHAR(250) NOT NULL,
    existenciaProducto INT NOT NULL,
    precioProducto DOUBLE PRECISION NOT NULL,
    idCategoria BIGINT,
    FOREIGN KEY (idCategoria) REFERENCES categoria(idCategoria)
);
